######################################################################
# Automatically generated by qmake (2.01a) Wed Feb 1 02:31:01 2017
######################################################################

TEMPLATE = app
TARGET = Acid.Cam.v2.Qt
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += main_window.h new_dialog.h plugin.h qtheaders.h select_image.h
SOURCES += main.cpp main_window.cpp new_dialog.cpp plugin.cpp select_image.cpp
